### PR TITLE
Create DaytonaNSE.htm

### PR DESCRIPTION
**Pull request by Krakatoa75**
Adding NSE - First time so be gentle

### CODE REVIEW

**Comment by TheKitBoi** [comment]
what about adding it in compatibility.html that where the links go

**Comment by Krakatoa75** [comment]
Ah I didn't know about that file. Its been updated,

**Comment by TheKitBoi** [comment]
also i see a name mistake.
its Daytona3NSE
to make it accurate to TPUI Profiles

**Comment by Krakatoa75** [comment]
That better? If not I’ll fix it tomorrow. Thanks for the help.

**Comment by TheKitBoi** [comment]
your ready to go on the merge

**Pull request merged**
